# Configuração do Nome do Aplicativo
spring.application.name=concorrencia

# Configuração da Conexão com o Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:dbconcorrencia;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuração do Console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Porta do Servidor (Padrão 8080 para o Spring Boot rodar localmente)
server.port=8080
